### ISSUE TITLE
todo Sistema de cuentas y logueo

### ISSUE THREAD

**Issue by cpbeto** [ao-libre/finisterra#363]
**todo:**
- [ ] Hay un bug que permite crear un PJ en un slot usado y sobreescribir el personaje existente.
- [ ] Hacer chequeos de seguridad en el logueo de PJs: verificar que el request viene de la misma conexión en que se logueó la cuenta, etc.
- [ ] Armar una tabla global de usuarios conectados que relacione username, playerID, connectionID, etc. Creo que se usaría en varios lugares y valdría la pena.

**extra:**
- [ ] Mantener registro de la fecha e IP de las conexiones.

**Comment by cpbeto** [comment]
Sobreescribir un personaje existente no es un bug, es intencionado. Ver `UserSystem.create()`.
Igualmente se podría pedir alguna confirmación o algo así.

**Comment by bestiardo** [comment]
buenas. sobre los personajes que se sobrescriben. 
fue intencional la forma en que esta echo. 
Lo había echo así porque en un primer momento pensaba crear un botón para borrar los personajes ya que el limite de personajes por cuenta es 6, pero al final puse solo el botón de crear (digámoslo por que me resulto mas fácil de hacerlo y con el tiempo se podría cambiar por botón eliminar si ya existe 1 personaje creado en ese slot de la cuenta) y que este borre el anterior personaje. para no quedar con archivos de pj creados a los cuales la cuenta ya no puede acceder, lo que hacia que te queden mucha basura en la carpeta de personajes

**Comment by cpbeto** [comment]
@bestiardo Genial 👍🏻
